### ISSUE TITLE
[NPU Runner Request] Let workflows run on NPU runners in cosdt org

### ISSUE THREAD

**Issue by shink** [opensourceways/ascend-ci-permission#1]
```yml
org-name: cosdt
github-app:
  installation-id: unknown
runner-group:
  group-name: linux-arm64-npu
runner-set:
  npu-counts: 1, 2
```
