### ISSUE TITLE
[NPU REQUEST] Add {org-name} to NPU Runners

### ISSUE THREAD

**Issue by cllouud** [opensourceways/ascend-ci-permission#3]
Welcome to use this template to submit an issue to add your organization to the NPU operator. Please follow the instructions below to fill in the relevant information so that we can process your request more efficiently.

```yaml
org-name:  org
github-app: 
  instalation-id: 1111 
runner-group: 
  group-name:  ascend-ci
runner-set: 
  npu-counts: 1,2
```

| Field | Description | Example | Required |
|------|------|------|-----|
| `org-name` | Full name of the organization | `awesome-ai-org` | ✅ |
| `github-app.installation-id` | Installation ID after installing ascend-runner-mgmt | `11111111` | ✅ |
| `runner-group.group-name` | The group name of the configured runner group | `ascend-ci` | ✅ |
| `runner-set.npu-counts` | The number array of NPU chip | `1,2` | ✅ |
